Ipfabric ssl verification
nautobot/nautobot-plugin-chatops-ipfabric pull request #65
Opened 2022-01-18 17:56 UTC by justinjeffery-ipf

Added SSL verification for IP Fabric to integrate with self-signed instances.

2022-01-18 17:57 UTC, justinjeffery-ipf commented
#65

2022-01-19 13:32 UTC, chadell approved these changes
LGTM

2022-01-19 14:57 UTC, pke11y requested changes
Looks great! Thanks for the PR. One suggestion.

2022-01-19 14:57 UTC, pke11y commented on development/nautobot_config.py
> +        "IPFABRIC_VERIFY": os.environ.get("IPFABRIC_VERIFY", True),
Could you wrap that with the `is_truthy` function for safety.
```suggestion
        "IPFABRIC_VERIFY": is_truthy(os.environ.get("IPFABRIC_VERIFY", True)),
```

2022-01-19 22:24 UTC, pke11y approved these changes
Nice job. Thanks!

2022-01-19 22:26 UTC, merged